### ISSUE TITLE
[Question] How often are the rankings updated and is there a way to force update the rankings/avatar?

### ISSUE THREAD

**Issue by Huanzhang89** [telunc/pinkbean#1]
I've noticed that the !rank feature is usually at least 2 days out of sync, and can't seem to find a way to force pull updates from the server

**Comment by telunc** [comment]
I use Cloudflare to cache player rankings. It will persist about 12 hours. After Nexon updated player ranking (you see ranking on their site), Pink Bean ranking should reset  within **< 12 hours**.

Nexon updates ranking daily (24 hours). Max time for Pink Bean's cache to expire is half a day (12 hours). This means the maximum wait time for your in game ranking to update is maximum **36 hours**.

I hope this helps :)
